name: Ximalaya for Xiaozhi AI

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    # 在北京时间6点、12点、18点启动（UTC时间22点、4点、10点）
    - cron: '0 22 * * *'
    - cron: '0 4 * * *'
    - cron: '0 10 * * *'

env:
  MCP_ENDPOINT: ${{ secrets.MCP_ENDPOINT }}

jobs:
  run-ximalaya-service:
    runs-on: ubuntu-latest
    timeout-minutes: 355  # 5小时55分钟，接近6小时限制

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Check Beijing time
      id: time_check
      run: |
        # 获取UTC时间并计算北京时间
        current_hour_utc=$(date -u +%H)
        current_hour_beijing=$(( (current_hour_utc + 8) % 24 ))
        
        echo "当前UTC时间: $(date -u)"
        echo "当前北京时间: 约 $current_hour_beijing 点"
        
        # 检查是否在0-6点之间
        if [ $current_hour_beijing -ge 0 ] && [ $current_hour_beijing -lt 6 ]; then
          echo "当前为北京时间0-6点，停止服务运行"
          echo "should_run=false" >> $GITHUB_OUTPUT
        else
          echo "当前为北京时间6-24点，启动服务"
          echo "should_run=true" >> $GITHUB_OUTPUT
        fi

    - name: Skip if in quiet hours
      if: steps.time_check.outputs.should_run == 'false'
      run: |
        echo "跳过服务执行，当前为静默时段（北京时间0-6点）"
        exit 0

    - name: Run Ximalaya Service
      if: steps.time_check.outputs.should_run == 'true'
      env:
        MCP_ENDPOINT: ${{ secrets.MCP_ENDPOINT }}
      run: |
        echo "启动独立听书服务..."
        python mcp_pipe.py ximalaya.py

    - name: Upload service logs (if any)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ximalaya-service-logs
        path: |
          *.log
        retention-days: 1
